name: Format Check
on: [push, pull_request]

jobs:
  tests:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses:
          - actions/checkout@v3
          - actions/setup-node@v3
      - run:
          - npm install
          - npm run lint:ci
